version: '3.8'
services:
  main:
    platform: linux/x86_64
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env


