export const UserErrors = {
  USER_NOT_FOUND: 'U001 - USER NOT FOUND',
  USER_BALANCE_NOT_FOUND: 'U002 - USER BALANCE NOT FOUND',
  USER_BALANCE_ID_REQUIRED: 'U003 - USER ID IS REQUIRED',
  INSUFFICIENT_BALANCE: 'U004 - INSUFFICIENT BALANCE',
  USERNAME_EXISTS: 'U005 - USERNAME ALREADY EXISTS',
};
