# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - truenorth-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://truenorth.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7ee5ed7e8dc64ed2902afe19ad7eb73f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7a08687108c144cb8ca837dc5fe6eb7c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: truenorth.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ee5ed7e8dc64ed2902afe19ad7eb73f }}/api/main:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'truenorth-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d5a22c89f34e42af83091ef0886cd872 }}
        images: 'truenorth.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ee5ed7e8dc64ed2902afe19ad7eb73f }}/api/main:${{ github.sha }}'